# Generated by Django 5.0.3 on 2024-03-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
